// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eZeljeznice.WebAPI.Database;

namespace eZeljeznice.WebAPI.Migrations
{
    [DbContext(typeof(IB170285Context))]
    [Migration("20210119160044_migr4")]
    partial class migr4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Gradovi", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GradID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradId")
                        .HasName("PK__Gradovi__B0F3C984A618A983");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            GradId = 1,
                            Naziv = "Docker test2",
                            Sadrzaj = "Docker test2"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Karte", b =>
                {
                    b.Property<int>("KartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RedniBrojSjedista")
                        .HasColumnType("int");

                    b.Property<int?>("RedniBrojVagona")
                        .HasColumnType("int");

                    b.HasKey("KartaId")
                        .HasName("PK__Karte__EC3FA98E79DF499B");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KorisnikID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnic__80B06D61BA5B40FA");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            DatumRodjenja = new DateTime(2021, 1, 19, 17, 0, 43, 520, DateTimeKind.Local).AddTicks(6346),
                            Email = "desktop@mail.com",
                            Ime = "test",
                            KorisnickoIme = "desktop",
                            LozinkaHash = "KjU9Eb6QhxC+aNEXdm6cDlDLkRQ=",
                            LozinkaSalt = "9IkPM47ay45XOr0Ea5pbTg==",
                            Prezime = "test"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Kupci", b =>
                {
                    b.Property<int>("KupacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KupacID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("KupacId")
                        .HasName("PK__Kupci__A9593C7BAA97602F");

                    b.ToTable("Kupci");

                    b.HasData(
                        new
                        {
                            KupacId = 1,
                            DatumRegistracije = new DateTime(2021, 1, 19, 17, 0, 43, 528, DateTimeKind.Local).AddTicks(2733),
                            Email = "mobile@mail.com",
                            Ime = "test",
                            KorisnickoIme = "mobile",
                            LozinkaHash = "KmYv6L2N5zHaKvquJkjLQMDH73E=",
                            LozinkaSalt = "2HGgKnDTh9X3Ns+pKCDi4A==",
                            Prezime = "test"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.Property<int>("ProdanaKartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProdanaKartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("DatumProdaje")
                        .HasColumnType("date");

                    b.Property<double?>("KonacnaCijena")
                        .HasColumnType("float");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Popust")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("ProdanaKartaId")
                        .HasName("PK__Kupljene__CB8E62892CC2A10F");

                    b.HasIndex("KupacId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("KupljeneKarte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Obavjestenja", b =>
                {
                    b.Property<int>("ObavjestenjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ObavjestenjaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObavjestenjaID")
                        .HasName("PK__Obavjest__C87A815D68EC0B31");

                    b.ToTable("Obavjestenja");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.Property<int>("PretragaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PretragaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnName("Ocjena")
                        .HasColumnType("int");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaID")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("PretragaId")
                        .HasName("PK__Pretrage__75C8FA1B23B7AAC2");

                    b.HasIndex("KupacId");

                    b.HasIndex("RelacijaId");

                    b.HasIndex("RezervacijaID");

                    b.ToTable("Pretrage");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.Property<int>("PutovanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DatumPolaska")
                        .HasColumnType("date");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("VrijemeDolaska")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("VrijemePolaska")
                        .HasColumnType("time");

                    b.HasKey("PutovanjeId")
                        .HasName("PK__Putovanj__D47C40F973E85F36");

                    b.HasIndex("RelacijaId");

                    b.ToTable("Putovanja");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.Property<int>("RelacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ZeljeznickaStanicaDoid")
                        .HasColumnName("ZeljeznickaStanicaDOID")
                        .HasColumnType("int");

                    b.Property<int?>("ZeljeznickaStanicaOdid")
                        .HasColumnName("ZeljeznickaStanicaODID")
                        .HasColumnType("int");

                    b.HasKey("RelacijaId")
                        .HasName("PK__Relacije__545AFBE54D92C334");

                    b.HasIndex("ZeljeznickaStanicaDoid");

                    b.HasIndex("ZeljeznickaStanicaOdid");

                    b.ToTable("Relacije");

                    b.HasData(
                        new
                        {
                            RelacijaId = 1,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 2,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 3,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 4,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 5,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 6,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 7,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 8,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 9,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 10,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 11,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 12,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 13,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 14,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 15,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 16,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 17,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 18,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 19,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 20,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 21,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 22,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 23,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 24,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 25,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 26,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 27,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 28,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 29,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 30,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 31,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 32,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 33,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 34,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 35,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 36,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 37,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 38,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 39,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 40,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 41,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 42,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 43,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 44,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 45,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 46,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 47,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 48,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 49,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 7
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.Property<int>("RezervacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRezervacije")
                        .HasColumnType("datetime");

                    b.Property<int?>("KartaId")
                        .HasColumnName("KartaID")
                        .HasColumnType("int");

                    b.Property<bool?>("Kompletirana")
                        .HasColumnType("bit");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("PutovanjeId")
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int");

                    b.HasKey("RezervacijaId")
                        .HasName("PK__Rezervac__CABA44FDB6409F3A");

                    b.HasIndex("KartaId");

                    b.HasIndex("KupacId");

                    b.HasIndex("PutovanjeId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.Property<int>("ZeljeznickaStanicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ZeljeznickaStanicaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("ZeljeznickaStanicaId")
                        .HasName("PK__Zeljezni__8FEBF7C4CFE3D4D0");

                    b.HasIndex("GradId");

                    b.ToTable("ZeljeznickeStanice");

                    b.HasData(
                        new
                        {
                            ZeljeznickaStanicaId = 1,
                            Adresa = "Halida Kajtaza 10",
                            Email = "ztsarajevo@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Sarajevo",
                            Telefon = "033251251"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 2,
                            Adresa = "Ložionička 12",
                            Email = "zsmostar@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Mostar",
                            Telefon = "036565565"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 3,
                            Adresa = "Radnička 23",
                            Email = "zttuzla@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Tuzla",
                            Telefon = "035458754"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 4,
                            Adresa = "Trg pobjede 56",
                            Email = "ztbanjaluka@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Banja Luka",
                            Telefon = "051478724"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 5,
                            Adresa = "Strojarska cesta 11",
                            Email = "zkzagreb@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Zagreb",
                            Telefon = "+385013333200"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 6,
                            Adresa = "Dubrovačka 11",
                            Email = "zksplit@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Split",
                            Telefon = "+385078924233"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 7,
                            Adresa = "Jurija Gagarina 33",
                            Email = "ztbeograd@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Beograd",
                            Telefon = "+381112222300"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("Korisnici")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Korisnici__GradI__1BFD2C07");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__KupljeneK__Kupac__01142BA1");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacija")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("RezervacijaId")
                        .HasConstraintName("FK__KupljeneK__Rezer__4F7CD00D");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Pretrage")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Pretrage__KupacI__32E0915F");

                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Pretrage")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Pretrage__Relaci__31EC6D26");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacije")
                        .WithMany("Pretrage")
                        .HasForeignKey("RezervacijaID")
                        .HasConstraintName("FK__Pretrage__Rezervacije__01142BA1");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Putovanja")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Putovanja__Relac__267ABA7A");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaDo")
                        .WithMany("RelacijeZeljeznickaStanicaDo")
                        .HasForeignKey("ZeljeznickaStanicaDoid")
                        .HasConstraintName("FK__Relacije__Zeljez__164452B1");

                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaOd")
                        .WithMany("RelacijeZeljeznickaStanicaOd")
                        .HasForeignKey("ZeljeznickaStanicaOdid")
                        .HasConstraintName("FK__Relacije__Zeljez__15502E78");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Karte", "Karta")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KartaId")
                        .HasConstraintName("FK__Rezervaci__Karta__2D27B809");

                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Rezervaci__Kupac__2B3F6F97");

                    b.HasOne("eZeljeznice.WebAPI.Database.Putovanja", "Putovanje")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutovanjeId")
                        .HasConstraintName("FK__Rezervaci__Putov__2C3393D0");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("ZeljeznickeStanice")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Zeljeznic__GradI__1273C1CD");
                });
#pragma warning restore 612, 618
        }
    }
}
