// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eZeljeznice.WebAPI.Database;

namespace eZeljeznice.WebAPI.Migrations
{
    [DbContext(typeof(IB170285Context))]
    [Migration("20210119164137_migr6")]
    partial class migr6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Gradovi", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GradID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradId")
                        .HasName("PK__Gradovi__B0F3C984A618A983");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            GradId = 1,
                            Naziv = "Docker test2",
                            Sadrzaj = "Docker test2"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Karte", b =>
                {
                    b.Property<int>("KartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RedniBrojSjedista")
                        .HasColumnType("int");

                    b.Property<int?>("RedniBrojVagona")
                        .HasColumnType("int");

                    b.HasKey("KartaId")
                        .HasName("PK__Karte__EC3FA98E79DF499B");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KorisnikID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnic__80B06D61BA5B40FA");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            DatumRodjenja = new DateTime(2021, 1, 19, 17, 41, 36, 416, DateTimeKind.Local).AddTicks(3316),
                            Email = "desktop@mail.com",
                            Ime = "test",
                            KorisnickoIme = "desktop",
                            LozinkaHash = "X9jHX9TvSKtq5zdFPFEhu2mScuo=",
                            LozinkaSalt = "+vQfnURDOtmfHx+21ShNpg==",
                            Prezime = "test"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Kupci", b =>
                {
                    b.Property<int>("KupacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KupacID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("KupacId")
                        .HasName("PK__Kupci__A9593C7BAA97602F");

                    b.ToTable("Kupci");

                    b.HasData(
                        new
                        {
                            KupacId = 1,
                            DatumRegistracije = new DateTime(2021, 1, 19, 17, 41, 36, 426, DateTimeKind.Local).AddTicks(9753),
                            Email = "mobile@mail.com",
                            Ime = "test",
                            KorisnickoIme = "mobile",
                            LozinkaHash = "MgUhFwDOhJ3TbAMWhqvAIop8nWo=",
                            LozinkaSalt = "66smX8rvVkzoPuJHM6shTw==",
                            Prezime = "test"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.Property<int>("ProdanaKartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProdanaKartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("DatumProdaje")
                        .HasColumnType("date");

                    b.Property<double?>("KonacnaCijena")
                        .HasColumnType("float");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Popust")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("ProdanaKartaId")
                        .HasName("PK__Kupljene__CB8E62892CC2A10F");

                    b.HasIndex("KupacId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("KupljeneKarte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Obavjestenja", b =>
                {
                    b.Property<int>("ObavjestenjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ObavjestenjaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObavjestenjaID")
                        .HasName("PK__Obavjest__C87A815D68EC0B31");

                    b.ToTable("Obavjestenja");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.Property<int>("PretragaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PretragaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnName("Ocjena")
                        .HasColumnType("int");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaID")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("PretragaId")
                        .HasName("PK__Pretrage__75C8FA1B23B7AAC2");

                    b.HasIndex("KupacId");

                    b.HasIndex("RelacijaId");

                    b.HasIndex("RezervacijaID");

                    b.ToTable("Pretrage");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.Property<int>("PutovanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DatumPolaska")
                        .HasColumnType("date");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("VrijemeDolaska")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("VrijemePolaska")
                        .HasColumnType("time");

                    b.HasKey("PutovanjeId")
                        .HasName("PK__Putovanj__D47C40F973E85F36");

                    b.HasIndex("RelacijaId");

                    b.ToTable("Putovanja");

                    b.HasData(
                        new
                        {
                            PutovanjeId = 1,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 1,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 2,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 2,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 3,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 3,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 4,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 4,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 5,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 5,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 6,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 6,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 7,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 7,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 8,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 8,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 9,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 9,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 10,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 10,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 11,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 11,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 12,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 12,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 13,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 13,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 14,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 14,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 15,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 15,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 16,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 16,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 17,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 17,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 18,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 18,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 19,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 19,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 20,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 20,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 21,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 21,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 22,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 22,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 23,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 23,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 24,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 24,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 25,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 25,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 26,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 26,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 27,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 27,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 28,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 28,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 29,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 29,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 30,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 30,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 31,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 31,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 32,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 32,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 33,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 33,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 34,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 34,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 35,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 35,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 36,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 36,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 37,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 37,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 38,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 38,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 39,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 39,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 40,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 40,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 41,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 41,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 42,
                            Cijena = 5.5,
                            DatumPolaska = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 42,
                            VrijemeDolaska = new TimeSpan(0, 10, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 43,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 1,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 44,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 2,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 45,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 3,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 46,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 4,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 47,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 5,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 48,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 6,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 49,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 7,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 50,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 8,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 51,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 9,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 52,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 10,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 53,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 11,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 54,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 12,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 55,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 13,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 56,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 14,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 57,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 15,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 58,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 16,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 59,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 17,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 60,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 18,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 61,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 19,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 62,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 20,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 63,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 21,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 64,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 22,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 65,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 23,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 66,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 24,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 67,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 25,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 68,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 26,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 69,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 27,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 70,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 28,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 71,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 29,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 72,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 30,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 73,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 31,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 74,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 32,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 75,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 33,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 76,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 34,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 77,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 35,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 78,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 36,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 79,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 37,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 80,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 38,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 81,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 39,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 82,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 40,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 83,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 41,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 84,
                            Cijena = 5.75,
                            DatumPolaska = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 42,
                            VrijemeDolaska = new TimeSpan(0, 11, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 4, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 85,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 1,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 86,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 2,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 87,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 3,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 88,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 4,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 89,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 5,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 90,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 6,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 91,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 7,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 92,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 8,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 93,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 9,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 94,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 10,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 95,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 11,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 96,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 12,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 97,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 13,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 98,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 14,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 99,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 15,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 100,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 16,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 101,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 17,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 102,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 18,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 103,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 19,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 104,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 20,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 105,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 21,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 106,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 22,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 107,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 23,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 108,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 24,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 109,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 25,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 110,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 26,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 111,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 27,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 112,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 28,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 113,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 29,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 114,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 30,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 115,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 31,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 116,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 32,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 117,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 33,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 118,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 34,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 119,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 35,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 120,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 36,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 121,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 37,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 122,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 38,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 123,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 39,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 124,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 40,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 125,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 41,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        },
                        new
                        {
                            PutovanjeId = 126,
                            Cijena = 7.9500000000000002,
                            DatumPolaska = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            RelacijaId = 42,
                            VrijemeDolaska = new TimeSpan(0, 12, 30, 0, 0),
                            VrijemePolaska = new TimeSpan(0, 5, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.Property<int>("RelacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ZeljeznickaStanicaDoid")
                        .HasColumnName("ZeljeznickaStanicaDOID")
                        .HasColumnType("int");

                    b.Property<int?>("ZeljeznickaStanicaOdid")
                        .HasColumnName("ZeljeznickaStanicaODID")
                        .HasColumnType("int");

                    b.HasKey("RelacijaId")
                        .HasName("PK__Relacije__545AFBE54D92C334");

                    b.HasIndex("ZeljeznickaStanicaDoid");

                    b.HasIndex("ZeljeznickaStanicaOdid");

                    b.ToTable("Relacije");

                    b.HasData(
                        new
                        {
                            RelacijaId = 1,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 2,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 3,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 4,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 5,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 6,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 1
                        },
                        new
                        {
                            RelacijaId = 7,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 8,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 9,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 10,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 11,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 12,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 2
                        },
                        new
                        {
                            RelacijaId = 13,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 14,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 15,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 16,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 17,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 18,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 3
                        },
                        new
                        {
                            RelacijaId = 19,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 20,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 21,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 22,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 23,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 24,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 4
                        },
                        new
                        {
                            RelacijaId = 25,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 26,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 27,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 28,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 29,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 30,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 5
                        },
                        new
                        {
                            RelacijaId = 31,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 32,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 33,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 34,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 35,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 36,
                            ZeljeznickaStanicaDoid = 7,
                            ZeljeznickaStanicaOdid = 6
                        },
                        new
                        {
                            RelacijaId = 37,
                            ZeljeznickaStanicaDoid = 1,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 38,
                            ZeljeznickaStanicaDoid = 2,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 39,
                            ZeljeznickaStanicaDoid = 3,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 40,
                            ZeljeznickaStanicaDoid = 4,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 41,
                            ZeljeznickaStanicaDoid = 5,
                            ZeljeznickaStanicaOdid = 7
                        },
                        new
                        {
                            RelacijaId = 42,
                            ZeljeznickaStanicaDoid = 6,
                            ZeljeznickaStanicaOdid = 7
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.Property<int>("RezervacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRezervacije")
                        .HasColumnType("datetime");

                    b.Property<int?>("KartaId")
                        .HasColumnName("KartaID")
                        .HasColumnType("int");

                    b.Property<bool?>("Kompletirana")
                        .HasColumnType("bit");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("PutovanjeId")
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int");

                    b.HasKey("RezervacijaId")
                        .HasName("PK__Rezervac__CABA44FDB6409F3A");

                    b.HasIndex("KartaId");

                    b.HasIndex("KupacId");

                    b.HasIndex("PutovanjeId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.Property<int>("ZeljeznickaStanicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ZeljeznickaStanicaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("ZeljeznickaStanicaId")
                        .HasName("PK__Zeljezni__8FEBF7C4CFE3D4D0");

                    b.HasIndex("GradId");

                    b.ToTable("ZeljeznickeStanice");

                    b.HasData(
                        new
                        {
                            ZeljeznickaStanicaId = 1,
                            Adresa = "Halida Kajtaza 10",
                            Email = "ztsarajevo@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Sarajevo",
                            Telefon = "033251251"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 2,
                            Adresa = "Ložionička 12",
                            Email = "zsmostar@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Mostar",
                            Telefon = "036565565"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 3,
                            Adresa = "Radnička 23",
                            Email = "zttuzla@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Tuzla",
                            Telefon = "035458754"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 4,
                            Adresa = "Trg pobjede 56",
                            Email = "ztbanjaluka@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Banja Luka",
                            Telefon = "051478724"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 5,
                            Adresa = "Strojarska cesta 11",
                            Email = "zkzagreb@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Zagreb",
                            Telefon = "+385013333200"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 6,
                            Adresa = "Dubrovačka 11",
                            Email = "zksplit@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Split",
                            Telefon = "+385078924233"
                        },
                        new
                        {
                            ZeljeznickaStanicaId = 7,
                            Adresa = "Jurija Gagarina 33",
                            Email = "ztbeograd@hotmail.com",
                            GradId = 1,
                            Naziv = "Ž.S. Beograd",
                            Telefon = "+381112222300"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("Korisnici")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Korisnici__GradI__1BFD2C07");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__KupljeneK__Kupac__01142BA1");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacija")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("RezervacijaId")
                        .HasConstraintName("FK__KupljeneK__Rezer__4F7CD00D");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Pretrage")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Pretrage__KupacI__32E0915F");

                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Pretrage")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Pretrage__Relaci__31EC6D26");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacije")
                        .WithMany("Pretrage")
                        .HasForeignKey("RezervacijaID")
                        .HasConstraintName("FK__Pretrage__Rezervacije__01142BA1");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Putovanja")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Putovanja__Relac__267ABA7A");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaDo")
                        .WithMany("RelacijeZeljeznickaStanicaDo")
                        .HasForeignKey("ZeljeznickaStanicaDoid")
                        .HasConstraintName("FK__Relacije__Zeljez__164452B1");

                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaOd")
                        .WithMany("RelacijeZeljeznickaStanicaOd")
                        .HasForeignKey("ZeljeznickaStanicaOdid")
                        .HasConstraintName("FK__Relacije__Zeljez__15502E78");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Karte", "Karta")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KartaId")
                        .HasConstraintName("FK__Rezervaci__Karta__2D27B809");

                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Rezervaci__Kupac__2B3F6F97");

                    b.HasOne("eZeljeznice.WebAPI.Database.Putovanja", "Putovanje")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutovanjeId")
                        .HasConstraintName("FK__Rezervaci__Putov__2C3393D0");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("ZeljeznickeStanice")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Zeljeznic__GradI__1273C1CD");
                });
#pragma warning restore 612, 618
        }
    }
}
