// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eZeljeznice.WebAPI.Database;

namespace eZeljeznice.WebAPI.Migrations
{
    [DbContext(typeof(IB170285Context))]
    [Migration("20210119005031_data")]
    partial class data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Gradovi", b =>
                {
                    b.Property<int>("GradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GradID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradId")
                        .HasName("PK__Gradovi__B0F3C984A618A983");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            GradId = 100,
                            Naziv = "Docker test",
                            Sadrzaj = "Docker test"
                        });
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Karte", b =>
                {
                    b.Property<int>("KartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RedniBrojSjedista")
                        .HasColumnType("int");

                    b.Property<int?>("RedniBrojVagona")
                        .HasColumnType("int");

                    b.HasKey("KartaId")
                        .HasName("PK__Karte__EC3FA98E79DF499B");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KorisnikID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnic__80B06D61BA5B40FA");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Kupci", b =>
                {
                    b.Property<int>("KupacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KupacID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("KupacId")
                        .HasName("PK__Kupci__A9593C7BAA97602F");

                    b.ToTable("Kupci");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.Property<int>("ProdanaKartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProdanaKartaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("DatumProdaje")
                        .HasColumnType("date");

                    b.Property<double?>("KonacnaCijena")
                        .HasColumnType("float");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Popust")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("ProdanaKartaId")
                        .HasName("PK__Kupljene__CB8E62892CC2A10F");

                    b.HasIndex("KupacId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("KupljeneKarte");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Obavjestenja", b =>
                {
                    b.Property<int>("ObavjestenjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ObavjestenjaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObavjestenjaID")
                        .HasName("PK__Obavjest__C87A815D68EC0B31");

                    b.ToTable("Obavjestenja");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.Property<int>("PretragaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PretragaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnName("Ocjena")
                        .HasColumnType("int");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaID")
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int");

                    b.HasKey("PretragaId")
                        .HasName("PK__Pretrage__75C8FA1B23B7AAC2");

                    b.HasIndex("KupacId");

                    b.HasIndex("RelacijaId");

                    b.HasIndex("RezervacijaID");

                    b.ToTable("Pretrage");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.Property<int>("PutovanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DatumPolaska")
                        .HasColumnType("date");

                    b.Property<int?>("RelacijaId")
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("VrijemeDolaska")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("VrijemePolaska")
                        .HasColumnType("time");

                    b.HasKey("PutovanjeId")
                        .HasName("PK__Putovanj__D47C40F973E85F36");

                    b.HasIndex("RelacijaId");

                    b.ToTable("Putovanja");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.Property<int>("RelacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RelacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ZeljeznickaStanicaDoid")
                        .HasColumnName("ZeljeznickaStanicaDOID")
                        .HasColumnType("int");

                    b.Property<int?>("ZeljeznickaStanicaOdid")
                        .HasColumnName("ZeljeznickaStanicaODID")
                        .HasColumnType("int");

                    b.HasKey("RelacijaId")
                        .HasName("PK__Relacije__545AFBE54D92C334");

                    b.HasIndex("ZeljeznickaStanicaDoid");

                    b.HasIndex("ZeljeznickaStanicaOdid");

                    b.ToTable("Relacije");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.Property<int>("RezervacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RezervacijaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumRezervacije")
                        .HasColumnType("datetime");

                    b.Property<int?>("KartaId")
                        .HasColumnName("KartaID")
                        .HasColumnType("int");

                    b.Property<bool?>("Kompletirana")
                        .HasColumnType("bit");

                    b.Property<int?>("KupacId")
                        .HasColumnName("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("PutovanjeId")
                        .HasColumnName("PutovanjeID")
                        .HasColumnType("int");

                    b.HasKey("RezervacijaId")
                        .HasName("PK__Rezervac__CABA44FDB6409F3A");

                    b.HasIndex("KartaId");

                    b.HasIndex("KupacId");

                    b.HasIndex("PutovanjeId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.Property<int>("ZeljeznickaStanicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ZeljeznickaStanicaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("GradId")
                        .HasColumnName("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("ZeljeznickaStanicaId")
                        .HasName("PK__Zeljezni__8FEBF7C4CFE3D4D0");

                    b.HasIndex("GradId");

                    b.ToTable("ZeljeznickeStanice");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Korisnici", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("Korisnici")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Korisnici__GradI__1BFD2C07");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.KupljeneKarte", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__KupljeneK__Kupac__01142BA1");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacija")
                        .WithMany("KupljeneKarte")
                        .HasForeignKey("RezervacijaId")
                        .HasConstraintName("FK__KupljeneK__Rezer__4F7CD00D");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Pretrage", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Pretrage")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Pretrage__KupacI__32E0915F");

                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Pretrage")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Pretrage__Relaci__31EC6D26");

                    b.HasOne("eZeljeznice.WebAPI.Database.Rezervacije", "Rezervacije")
                        .WithMany("Pretrage")
                        .HasForeignKey("RezervacijaID")
                        .HasConstraintName("FK__Pretrage__Rezervacije__01142BA1");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Putovanja", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Relacije", "Relacija")
                        .WithMany("Putovanja")
                        .HasForeignKey("RelacijaId")
                        .HasConstraintName("FK__Putovanja__Relac__267ABA7A");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Relacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaDo")
                        .WithMany("RelacijeZeljeznickaStanicaDo")
                        .HasForeignKey("ZeljeznickaStanicaDoid")
                        .HasConstraintName("FK__Relacije__Zeljez__164452B1");

                    b.HasOne("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", "ZeljeznickaStanicaOd")
                        .WithMany("RelacijeZeljeznickaStanicaOd")
                        .HasForeignKey("ZeljeznickaStanicaOdid")
                        .HasConstraintName("FK__Relacije__Zeljez__15502E78");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.Rezervacije", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Karte", "Karta")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KartaId")
                        .HasConstraintName("FK__Rezervaci__Karta__2D27B809");

                    b.HasOne("eZeljeznice.WebAPI.Database.Kupci", "Kupac")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KupacId")
                        .HasConstraintName("FK__Rezervaci__Kupac__2B3F6F97");

                    b.HasOne("eZeljeznice.WebAPI.Database.Putovanja", "Putovanje")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutovanjeId")
                        .HasConstraintName("FK__Rezervaci__Putov__2C3393D0");
                });

            modelBuilder.Entity("eZeljeznice.WebAPI.Database.ZeljeznickeStanice", b =>
                {
                    b.HasOne("eZeljeznice.WebAPI.Database.Gradovi", "Grad")
                        .WithMany("ZeljeznickeStanice")
                        .HasForeignKey("GradId")
                        .HasConstraintName("FK__Zeljeznic__GradI__1273C1CD");
                });
#pragma warning restore 612, 618
        }
    }
}
